main: main.o Menu.o; \
g++ -o main -L C:\\SFML-2.5.1\\lib main.o Menu.o -lsfml-graphics -lsfml-audio -lsfml-network -lsfml-window -lsfml-system

main.o: main.cpp; \
g++ -c -I C:\\SFML-2.5.1\\include main.cpp

Menu.o: Menu.cpp; \
g++ -c -I C:\\SFML-2.5.1\\include Menu.cpp